# Generated by Django 4.0.4 on 2022-04-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_game_user_drawing_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drawing',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
