# Generated by Django 4.0.4 on 2022-04-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_user_drawing_save_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='drawing_save_data',
            new_name='canvas_data',
        ),
    ]
